# Generated by Django 4.2.2 on 2023-12-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apartamento", models.IntegerField()),
                ("valor", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Quarto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Hospedagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateField()),
                ("data_saida", models.DateField()),
                ("valor", models.FloatField()),
                (
                    "consumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospedagem.consumo",
                    ),
                ),
                (
                    "quarto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospedagem.quarto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=200)),
                (
                    "hospedagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospedagem.hospedagem",
                    ),
                ),
            ],
        ),
    ]
